name: padavanonly mt7986-ax6000 Builder

on:
  workflow_dispatch:
  repository_dispatch:
    types: [mt798x-update]

env:
  REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-24.10
  REPO_NAME: immortalwrt
  REPO_BRANCH: 2410
  OpenWrt_VERSION: 24.10
  OpenWrt_ARCH: mt7986
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: padavanonly/diy-part1-mt7986-ax6000.sh
  DIY_P2_SH: padavanonly/diy-part2-mt7986-ax6000.sh
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: 检查服务器配置
        run: |
          echo "警告⚠"
          echo "若分配的服务器性能不足，务必及时取消，重新运行！"
          echo "已知编译成功CPU型号：8370C,8171M"
          echo "已知性能不足CPU型号：8272CL,E5系列"
          echo "--------------------------CPU信息--------------------------"
          echo "CPU物理数量:$(cat /proc/cpuinfo| grep "physical id"| sort| uniq| wc -l)"
          echo -e "CPU核心及版本信息：$(cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c) \n"
          echo "--------------------------内存信息--------------------------"
          echo "已安装内存详细信息："
          sudo lshw -short -C memory | grep GiB
          echo -e "\n"
          echo "--------------------------硬盘信息--------------------------"
          echo -e  "硬盘数量：$(ls /dev/sd* | grep -v [1-9] | wc -l) \n"
          echo "硬盘详情："
          df -Th

      - name: 清理磁盘空间 (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: 检查磁盘检使用情况
        if: (!cancelled())
        run: df -hT

      - name: 准备完成
        uses: actions/checkout@main

      - name: 初始化编译环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo -E apt-get -qq update
          sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "${TZ}"
          sudo mkdir -p /workdir
          sudo chown $USER:$GROUPS /workdir

      - name: 下载固件源码
        working-directory: /workdir
        run: |
          df -hT $PWD
          git clone -b ${REPO_BRANCH} --single-branch --depth 1 ${REPO_URL} openwrt
          ln -sf /workdir/openwrt ${GITHUB_WORKSPACE}/openwrt

      - name: 加载自定义feeds
        run: |
          [ -e ${FEEDS_CONF} ] && mv ${FEEDS_CONF} openwrt/feeds.conf.default
          chmod +x ${DIY_P1_SH}
          cd openwrt
          ${GITHUB_WORKSPACE}/${DIY_P1_SH}

      - name: 更新并安装feeds
        run: |
          cd openwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: 加载默认config
        run: |
          cd openwrt
          cp -f defconfig/mt7986-ax6000.config .config
      
      - name: 加载自定义配置
        run: |
          chmod +x ${DIY_P2_SH}
          cd openwrt
          ${GITHUB_WORKSPACE}/${DIY_P2_SH}

      - name: 下载软件包
        id: package
        run: |
          cd openwrt
          make defconfig
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: 编译固件
        id: compile
        run: |
          cd openwrt
          echo -e "$(($(nproc) + 1)) thread compile"
          make -j$(($(nproc) + 1)) V=s || make -j1 || make -j1 V=s
          echo "status=success" >> $GITHUB_OUTPUT
          echo "COMPILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

      - name: 检查磁盘使用情况
        if: (!cancelled())
        run: df -hT

      - name: 列出固件文件
        if: steps.compile.outputs.status == 'success' && !cancelled()
        run: |
          cd openwrt/bin/targets/*/*
          echo -e "------------------------------- 文件列表 -------------------------------"
          ls
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV

      - name: 整理固件
        if: steps.compile.outputs.status == 'success' && !cancelled()
        run: |
          cp -rf openwrt/.config ${{ env.FIRMWARE }}/config
          cd ${{ env.FIRMWARE }}
          rm -rf packages
          rm -rf profiles.json
          rm -rf *.buildinfo
          rm -rf *.manifest
          rm -rf *kernel.bin
          echo -e "------------------------------- 文件列表 -------------------------------"
          ls

      - name: 生成发布标签
        id: tag
        if: steps.compile.outputs.status == 'success' && !cancelled()
        run: |
          echo "release_tag=${{ env.REPO_NAME }}_${{ env.OpenWrt_VERSION }}_${{ env.OpenWrt_ARCH }}_${{ env.COMPILE_DATE }}" >> ${GITHUB_OUTPUT}
          touch ${{ env.REPO_NAME }}-${{ env.OpenWrt_ARCH }}-release.txt
          echo "
          本固件为红米redmi-ax6000刷写固件，使用[H大的不死u-boot](https://github.com/hanwckf/bl-mt798x) 选择immortalwrt-110m分区刷入
          
          💻 架构: ${{ env.OpenWrt_ARCH }}

          📂 源码: ${{ env.REPO_URL }}

          🌳 分支: ${{ env.REPO_BRANCH }}

          ⏱️ 编译时间: ${{ env.COMPILE_DATE }}

          🌐 管理地址: 192.168.1.1 , 子网掩码: 255.255.255.0

          👤 用户名: root

          🔒 密码: password 
          
          " > ${{ env.REPO_NAME }}-${{ env.OpenWrt_ARCH }}-release.txt
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: 发布固件到 Releases
        uses: softprops/action-gh-release@v2
        if: steps.tag.outputs.status == 'success' && !cancelled()
        with:
          tag_name: ${{ steps.tag.outputs.release_tag }}
          body_path: ${{ env.REPO_NAME }}-${{ env.OpenWrt_ARCH }}-release.txt
          files: ${{ env.FIRMWARE }}/*

      - name: 删除 Releases 旧版本
        uses: dev-drprasad/delete-older-releases@master
        if: steps.tag.outputs.status == 'success' && !cancelled()
        with:
          keep_latest: 2
          delete_tags: true
          delete_tag_pattern: ^${{ env.REPO_NAME }}_${{ env.OpenWrt_VERSION }}_${{ env.OpenWrt_ARCH }}_.*$
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
